apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ma1sd.fullname" . }}
  labels:
{{ include "ma1sd.labels" . | indent 4 }}
data:
{{- if .Values.signing_key }}
  signing.key: {{ required "Generate a signing key (see README)" .Values.signing_key | toYaml | b64enc | quote }}
{{- end }}
  ma1sd.yaml: {{ .Values.config | toYaml | b64enc | quote }}
